Upgrade rancher to version 0.5.0
nhsuk/ci-deployment pull request #15
Opened 2017-03-03 10:15 UTC by neilbmclaughlin

2017-03-08 07:50 UTC, beseven approved these changes
I'll leave this one to @adamgraves-choices as not familiar with the rancher CLI commands/versions. Looks ok from a layman POV.

2017-03-08 08:24 UTC, st3v3nhunt requested changes
Should the `bin/rancher` directory be ignored? i.e. does `.gitignore` need `bin/` adding to it?

2017-03-08 08:24 UTC, st3v3nhunt commented on install_rancher.sh
> +declare BIN="${1:-./bin}"
Is it worth documenting the ability to install to another dir anywhere?

2017-03-16 17:26 UTC, neilbmclaughlin commented
Deferring upgrade of rancher for now.

2017-03-16 17:26 UTC, closed without merging