Update readme and example .travis.yml to remove inaccuracies
nhsuk/ci-deployment pull request #24
Opened 2017-03-17 12:39 UTC by neilbmclaughlin

2017-03-19 11:05 UTC, st3v3nhunt requested changes

2017-03-19 11:05 UTC, st3v3nhunt commented on .travis.yml
> +  - ./scripts/ci-deployment/docker_ci.sh
This only needs changing when the submodule has been added to a non-default location. This is stated in the `README` already.
Making this change needs to update that commentary in the `README`. If that is going to happen I'd suggest making `scripts/` something more variable-esque so that it must be changed and is obviously required to be changed. Rather than something that looks like it might work.

2017-03-19 11:05 UTC, st3v3nhunt commented on .travis.yml
> +  - ./scripts/ci-deployment/rancher_pr_deploy.sh
Ditto line above

2017-03-19 11:05 UTC, st3v3nhunt commented on README.md
> +* If the Travis build has been triggered by a PR a new stack will be created within the `RANCHER_ENVIRONMENT` in Rancher. The rancher and docker templates used to build the stack are pulled from the
Unnecessary use of a subjective description e.g. `(imperfect)`. I'm suggesting it is removed. Unless there is something that can be linked to from Rancher stating that is the case.

2017-03-19 11:05 UTC, st3v3nhunt commented on README.md
> +* Image tag variable names in the rancher-compose.yml file should conform to a naming convention ({modified repo name}_DOCKER_IMAGE_TAG where {modified repo name} is the repo name in upper case with
Suggest having a specific example to aid understanding

2017-03-19 11:05 UTC, st3v3nhunt commented on README.md
> +1. Update that repo's `.travis.yml` to include the sections included within this repo's `.travis.yml`. (see [nhsuk/gp-finder](https://github.com/nhsuk/gp-finder) as an example of a repo using the scr
I don't think it is necessary to hand off to another repo here for an example, there should be enough information available in this repo. What happens when that repo changes?

2017-03-19 11:05 UTC, st3v3nhunt commented on README.md
> +| `SPLUNK_HEC_TOKEN` | YES | [HTTP Event Collector token](http://dev.splunk.com/view/event-collector/SP-CAAAE7C)                | | YES |
I believe this is no longer required now the logging is to `stdout`

2017-03-19 11:05 UTC, st3v3nhunt commented on README.md
> +| `RANCHER_TEMPLATE_NAME`| NO     | Name of directory where Rancher config is stored in [nhsuk-rancher-templates](https://github.com/nhsuk/nhsuk-rancher-templates) | `c2s-profiles` | YES |
Remove additional spaces after `NO` for consistency in formatting

2017-03-20 09:51 UTC, neilbmclaughlin commented
@st3v3nhunt - ready for merge.

2017-03-20 10:15 UTC, st3v3nhunt approved these changes

2017-03-20 10:15 UTC, merged